#! /usr/bin/env bash

echo "Creating S3 bucket..."

# Check for bucket name

if [ -z "$1" ]; then
    echo "No bucket name provided! - please provide a bucket name as the argument."
    exit 1
fi

bucket_name=$1

aws s3api create-bucket --bucket $bucket_name \
--create-bucket-configuration="LocationConstraint=eu-central-1" \
--query 'Location' \
--output json