#! /usr/env bash#! /usr/bin/env bash

echo "Deleting S3 bucket..."

# Check for bucket name

if [ -z "$1" ]; then
    echo "No bucket name provided! - please provide a bucket name as the argument."
    exit 1
fi

bucket_name=$1

aws s3api delete-bucket --bucket $bucket_name \
--output json 